/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { AffidavitRegistry } from "./AffidavitRegistry";
export * as factories from "./factories";
export { AffidavitRegistry__factory } from "./factories/AffidavitRegistry__factory";
