/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Affidavit } from "./Affidavit";
export * as factories from "./factories";
export { Affidavit__factory } from "./factories/Affidavit__factory";
